INSERT INTO ROLE VALUES (1, 'ADMIN');
INSERT INTO ROLE VALUES (2, 'USER');
INSERT INTO USER (USER_ID, ACTIVE, EMAIL, NAME, PASSWORD) VALUES
(1, 1, 'admin', 'admin', '$2a$10$fhs32M8NOoB5DCVs9g0MHuLfo1gchVJJ/1NfEGsyjXUhGElkP1/pa');
INSERT INTO USER_ROLE VALUES (1,1);